name: example_flutter
description: An example project for flutter-desktop-embedding.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  flare_flutter: 1.0.2
  # Desktop embedder plugins.
  # Note: In an actual project, these paths would include the
  # path from your application to the flutter_desktop_embedding
  # checkout.
  color_panel:
    path: ../plugins/color_panel
  file_chooser:
    path: ../plugins/file_chooser
  menubar:
    path: ../plugins/menubar

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/concept.gif
    - assets/reflectly.gif
    - assets/flutter_gallery.gif
    - assets/history.gif
    - assets/images/curve_bounce_in.png
    - assets/images/curve_bounce_in_out.png
    - assets/images/curve_bounce_out.png
    - assets/images/curve_decelerate.png
    - assets/images/curve_ease.png
    - assets/images/curve_ease_in.png
    - assets/images/curve_ease_in_out.png
    - assets/images/curve_ease_out.png
    - assets/images/curve_elastic_in.png
    - assets/images/curve_elastic_in_out.png
    - assets/images/curve_elastic_out.png
    - assets/images/curve_fast_out_slow_in.png
    - assets/images/curve_linear.png
    - assets/images/flare.png
    - assets/images/karlmax.png
    - flare_animation/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
